
// This file has been generated by the GUI designer. Do not modify.
namespace BibliographyMaker
{
	public partial class MainWindow
	{
		private global::Gtk.UIManager UIManager;
		private global::Gtk.Notebook notebook4;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.Frame frame1;
		private global::Gtk.Alignment GtkAlignment;
		private global::Gtk.VBox vbox1;
		private global::Gtk.HBox hbox1;
		private global::Gtk.HBox hbox4;
		private global::Gtk.Label fo;
		private global::Gtk.ComboBox type;
		private global::Gtk.VSeparator vseparator1;
		private global::Gtk.HBox hbox2;
		private global::Gtk.HBox hbox5;
		private global::Gtk.Label dop;
		private global::Gtk.Label d;
		private global::Gtk.Entry day;
		private global::Gtk.Label m;
		private global::Gtk.HBox hbox6;
		private global::Gtk.Entry month;
		private global::Gtk.Label y;
		private global::Gtk.Entry year;
		private global::Gtk.VBox vbox3;
		private global::Gtk.HSeparator hseparator1;
		private global::Gtk.HBox hbox7;
		private global::Gtk.Label label8;
		private global::Gtk.Entry title;
		private global::Gtk.VSeparator vseparator2;
		private global::Gtk.HBox hbox8;
		private global::Gtk.Label label9;
		private global::Gtk.Entry bibname;
		private global::Gtk.HBox hbox9;
		private global::Gtk.Label label10;
		private global::Gtk.Entry name;
		private global::Gtk.VBox vbox2;
		private global::Gtk.HBox hbox10;
		private global::Gtk.HBox hbox41;
		private global::Gtk.Label label6;
		private global::Gtk.Entry director;
		private global::Gtk.Label label11;
		private global::Gtk.Entry corpauth;
		private global::Gtk.HSeparator hseparator3;
		private global::Gtk.HSeparator hseparator4;
		private global::Gtk.HBox hbox11;
		private global::Gtk.Label label12;
		private global::Gtk.HBox hbox13;
		private global::Gtk.Entry pub;
		private global::Gtk.Label label13;
		private global::Gtk.Entry city;
		private global::Gtk.HBox hbox12;
		private global::Gtk.Label label14;
		private global::Gtk.Entry country;
		private global::Gtk.VBox vbox4;
		private global::Gtk.HBox hbox15;
		private global::Gtk.Label label15;
		private global::Gtk.HBox hbox17;
		private global::Gtk.Entry journal;
		private global::Gtk.Label label16;
		private global::Gtk.Entry article;
		private global::Gtk.HBox hbox16;
		private global::Gtk.Label label19;
		private global::Gtk.HBox hbox18;
		private global::Gtk.Entry volume;
		private global::Gtk.Label label20;
		private global::Gtk.Entry issue;
		private global::Gtk.HSeparator hseparator2;
		private global::Gtk.VBox vbox6;
		private global::Gtk.HBox hbox19;
		private global::Gtk.Label label1;
		private global::Gtk.Entry issn;
		private global::Gtk.HBox hbox20;
		private global::Gtk.Label label17;
		private global::Gtk.Entry isbn;
		private global::Gtk.HBox hbox21;
		private global::Gtk.Label label18;
		private global::Gtk.Entry loc;
		private global::Gtk.HBox hbox44;
		private global::Gtk.Label label38;
		private global::Gtk.Entry runtime;
		private global::Gtk.VBox vbox5;
		private global::Gtk.HBox hbox22;
		private global::Gtk.Label label21;
		private global::Gtk.Entry doi;
		private global::Gtk.HBox hbox23;
		private global::Gtk.Label label22;
		private global::Gtk.Entry url;
		private global::Gtk.VBox vbox7;
		private global::Gtk.HBox hbox3;
		private global::Gtk.Label label23;
		private global::Gtk.Entry medium;
		private global::Gtk.VBox vbox8;
		private global::Gtk.HBox hbox24;
		private global::Gtk.Label label24;
		private global::Gtk.Entry edition;
		private global::Gtk.HBox hbox25;
		private global::Gtk.Label label25;
		private global::Gtk.Entry institution;
		private global::Gtk.VBox vbox9;
		private global::Gtk.HBox hbox26;
		private global::Gtk.Label label26;
		private global::Gtk.Entry pubtype;
		private global::Gtk.HBox hbox27;
		private global::Gtk.Label label27;
		private global::Gtk.Entry chapter;
		private global::Gtk.VBox vbox10;
		private global::Gtk.HBox hbox28;
		private global::Gtk.Label label28;
		private global::Gtk.Entry pages;
		private global::Gtk.HBox hbox29;
		private global::Gtk.Label Series;
		private global::Gtk.Entry series;
		private global::Gtk.VBox vbox11;
		private global::Gtk.HBox hbox14;
		private global::Gtk.Label label30;
		private global::Gtk.Entry org;
		private global::Gtk.HBox hbox30;
		private global::Gtk.Label label31;
		private global::Gtk.Entry university;
		private global::Gtk.VBox vbox12;
		private global::Gtk.HBox hbox31;
		private global::Gtk.Label label32;
		private global::Gtk.Entry editor;
		private global::Gtk.HBox hbox32;
		private global::Gtk.Label label33;
		private global::Gtk.Entry translator;
		private global::Gtk.HBox hbox33;
		private global::Gtk.VBox vbox13;
		private global::Gtk.HBox hbox34;
		private global::Gtk.Label label34;
		private global::Gtk.Entry etcetera;
		private global::Gtk.HBox hbox35;
		private global::Gtk.Label label35;
		private global::Gtk.ScrolledWindow annotation2;
		private global::Gtk.TextView annotation;
		private global::Gtk.HBox hbox36;
		private global::Gtk.Label label29;
		private global::Gtk.HBox hbox42;
		private global::Gtk.Entry accessday;
		private global::Gtk.Label label36;
		private global::Gtk.HBox hbox43;
		private global::Gtk.Entry accessmonth;
		private global::Gtk.Label label37;
		private global::Gtk.Entry accessyear;
		private global::Gtk.Button Submit;
		private global::Gtk.Label Indexer;
		private global::Gtk.VBox vbox15;
		private global::Gtk.HBox hbox40;
		private global::Gtk.Button refresh;
		private global::Gtk.Button clear;
		private global::Gtk.Fixed fixed3;
		private global::Gtk.ScrolledWindow GtkScrolledWindow1;
		private global::Gtk.TextView dataview;
		private global::Gtk.Label label2;
		private global::Gtk.VBox vbox14;
		private global::Gtk.HBox hbox37;
		private global::Gtk.Label label3;
		private global::Gtk.ComboBox combobox1;
		private global::Gtk.HBox hbox38;
		private global::Gtk.Label label4;
		private global::Gtk.ComboBox combobox2;
		private global::Gtk.HBox hbox39;
		private global::Gtk.Label label5;
		private global::Gtk.ComboBox combobox3;
		private global::Gtk.Button list;
		private global::Gtk.Button Make;
		private global::Gtk.ScrolledWindow GtkScrolledWindow2;
		private global::Gtk.TextView textview2;
		private global::Gtk.Label label7;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget BibliographyMaker.MainWindow
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.Name = "BibliographyMaker.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("BiblioMaker");
			this.Icon = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./bibmake.png"));
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.BorderWidth = ((uint)(4));
			// Container child BibliographyMaker.MainWindow.Gtk.Container+ContainerChild
			this.notebook4 = new global::Gtk.Notebook ();
			this.notebook4.CanFocus = true;
			this.notebook4.Name = "notebook4";
			this.notebook4.CurrentPage = 2;
			this.notebook4.TabPos = ((global::Gtk.PositionType)(0));
			// Container child notebook4.Gtk.Notebook+NotebookChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.VscrollbarPolicy = ((global::Gtk.PolicyType)(0));
			this.GtkScrolledWindow.HscrollbarPolicy = ((global::Gtk.PolicyType)(2));
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			this.GtkScrolledWindow.BorderWidth = ((uint)(3));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			global::Gtk.Viewport w2 = new global::Gtk.Viewport ();
			w2.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.frame1 = new global::Gtk.Frame ();
			this.frame1.Name = "frame1";
			this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame1.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.fo = new global::Gtk.Label ();
			this.fo.Name = "fo";
			this.fo.LabelProp = global::Mono.Unix.Catalog.GetString ("Format");
			this.hbox4.Add (this.fo);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.fo]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.type = global::Gtk.ComboBox.NewText ();
			this.type.AppendText (global::Mono.Unix.Catalog.GetString ("Select One"));
			this.type.AppendText (global::Mono.Unix.Catalog.GetString ("Book"));
			this.type.AppendText (global::Mono.Unix.Catalog.GetString ("Print Journal Article"));
			this.type.AppendText (global::Mono.Unix.Catalog.GetString ("Book Review"));
			this.type.AppendText (global::Mono.Unix.Catalog.GetString ("Magazine"));
			this.type.AppendText (global::Mono.Unix.Catalog.GetString ("Daily Newspaper"));
			this.type.AppendText (global::Mono.Unix.Catalog.GetString ("Editorial Newspaper"));
			this.type.AppendText (global::Mono.Unix.Catalog.GetString ("Letter To Editor"));
			this.type.AppendText (global::Mono.Unix.Catalog.GetString ("Entire Website"));
			this.type.AppendText (global::Mono.Unix.Catalog.GetString ("Web Page"));
			this.type.AppendText (global::Mono.Unix.Catalog.GetString ("Online Journal"));
			this.type.AppendText (global::Mono.Unix.Catalog.GetString ("Online Book"));
			this.type.AppendText (global::Mono.Unix.Catalog.GetString ("Online Mag/News Article"));
			this.type.AppendText (global::Mono.Unix.Catalog.GetString ("Entire Blog"));
			this.type.AppendText (global::Mono.Unix.Catalog.GetString ("Response In Blog"));
			this.type.AppendText (global::Mono.Unix.Catalog.GetString ("Online Book Portion"));
			this.type.AppendText (global::Mono.Unix.Catalog.GetString ("CD-ROM"));
			this.type.AppendText (global::Mono.Unix.Catalog.GetString ("E-Mail"));
			this.type.AppendText (global::Mono.Unix.Catalog.GetString ("Video/Film"));
			this.type.AppendText (global::Mono.Unix.Catalog.GetString ("Podcast/Youtube"));
			this.type.AppendText (global::Mono.Unix.Catalog.GetString ("Lecture/Public Address"));
			this.type.AppendText (global::Mono.Unix.Catalog.GetString ("Thesis/Dissertation"));
			this.type.AppendText (global::Mono.Unix.Catalog.GetString ("Encyclopedia/Dictionary"));
			this.type.AppendText (global::Mono.Unix.Catalog.GetString ("Work in Anthology"));
			this.type.AppendText (global::Mono.Unix.Catalog.GetString ("Multi - Volume Work"));
			this.type.AppendText (global::Mono.Unix.Catalog.GetString ("Forward/Introduction"));
			this.type.AppendText (global::Mono.Unix.Catalog.GetString ("Preface/Afterword"));
			this.type.AppendText (global::Mono.Unix.Catalog.GetString ("GovPub"));
			this.type.Name = "type";
			this.type.Active = 0;
			this.hbox4.Add (this.type);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.type]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			this.hbox1.Add (this.hbox4);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.hbox4]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vseparator1 = new global::Gtk.VSeparator ();
			this.vseparator1.Name = "vseparator1";
			this.hbox1.Add (this.vseparator1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vseparator1]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.dop = new global::Gtk.Label ();
			this.dop.Name = "dop";
			this.dop.LabelProp = global::Mono.Unix.Catalog.GetString ("DOP");
			this.hbox5.Add (this.dop);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.dop]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.d = new global::Gtk.Label ();
			this.d.Name = "d";
			this.d.LabelProp = global::Mono.Unix.Catalog.GetString ("Day");
			this.hbox5.Add (this.d);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.d]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.day = new global::Gtk.Entry ();
			this.day.CanFocus = true;
			this.day.Name = "day";
			this.day.IsEditable = true;
			this.day.InvisibleChar = '•';
			this.hbox5.Add (this.day);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.day]));
			w9.Position = 2;
			this.hbox2.Add (this.hbox5);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.hbox5]));
			w10.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.m = new global::Gtk.Label ();
			this.m.Name = "m";
			this.m.LabelProp = global::Mono.Unix.Catalog.GetString ("Month");
			this.hbox2.Add (this.m);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.m]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox ();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.month = new global::Gtk.Entry ();
			this.month.CanFocus = true;
			this.month.Name = "month";
			this.month.IsEditable = true;
			this.month.InvisibleChar = '•';
			this.hbox6.Add (this.month);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.month]));
			w12.Position = 0;
			// Container child hbox6.Gtk.Box+BoxChild
			this.y = new global::Gtk.Label ();
			this.y.Name = "y";
			this.y.LabelProp = global::Mono.Unix.Catalog.GetString ("Year");
			this.hbox6.Add (this.y);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.y]));
			w13.Position = 1;
			w13.Expand = false;
			w13.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.year = new global::Gtk.Entry ();
			this.year.CanFocus = true;
			this.year.Name = "year";
			this.year.IsEditable = true;
			this.year.InvisibleChar = '•';
			this.hbox6.Add (this.year);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.year]));
			w14.Position = 2;
			this.hbox2.Add (this.hbox6);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.hbox6]));
			w15.Position = 2;
			this.hbox1.Add (this.hbox2);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.hbox2]));
			w16.Position = 2;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
			w17.Position = 0;
			w17.Expand = false;
			w17.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hseparator1 = new global::Gtk.HSeparator ();
			this.hseparator1.Name = "hseparator1";
			this.vbox3.Add (this.hseparator1);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hseparator1]));
			w18.Position = 0;
			w18.Expand = false;
			w18.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox ();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.label8 = new global::Gtk.Label ();
			this.label8.Name = "label8";
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Title");
			this.hbox7.Add (this.label8);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.label8]));
			w19.Position = 0;
			w19.Expand = false;
			w19.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.title = new global::Gtk.Entry ();
			this.title.CanFocus = true;
			this.title.Name = "title";
			this.title.IsEditable = true;
			this.title.InvisibleChar = '•';
			this.hbox7.Add (this.title);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.title]));
			w20.Position = 1;
			// Container child hbox7.Gtk.Box+BoxChild
			this.vseparator2 = new global::Gtk.VSeparator ();
			this.vseparator2.Name = "vseparator2";
			this.hbox7.Add (this.vseparator2);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.vseparator2]));
			w21.Position = 2;
			w21.Expand = false;
			w21.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox ();
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 6;
			// Container child hbox8.Gtk.Box+BoxChild
			this.label9 = new global::Gtk.Label ();
			this.label9.Name = "label9";
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("BibID");
			this.hbox8.Add (this.label9);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.label9]));
			w22.Position = 0;
			w22.Expand = false;
			w22.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.bibname = new global::Gtk.Entry ();
			this.bibname.CanFocus = true;
			this.bibname.Name = "bibname";
			this.bibname.IsEditable = true;
			this.bibname.InvisibleChar = '•';
			this.hbox8.Add (this.bibname);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.bibname]));
			w23.Position = 1;
			this.hbox7.Add (this.hbox8);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.hbox8]));
			w24.Position = 3;
			this.vbox3.Add (this.hbox7);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox7]));
			w25.Position = 1;
			w25.Expand = false;
			w25.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox9 = new global::Gtk.HBox ();
			this.hbox9.Name = "hbox9";
			this.hbox9.Spacing = 6;
			// Container child hbox9.Gtk.Box+BoxChild
			this.label10 = new global::Gtk.Label ();
			this.label10.Name = "label10";
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("Authors [First, Last, Middle; ]");
			this.hbox9.Add (this.label10);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.label10]));
			w26.Position = 0;
			w26.Expand = false;
			w26.Fill = false;
			// Container child hbox9.Gtk.Box+BoxChild
			this.name = new global::Gtk.Entry ();
			this.name.CanFocus = true;
			this.name.Name = "name";
			this.name.IsEditable = true;
			this.name.InvisibleChar = '•';
			this.hbox9.Add (this.name);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.name]));
			w27.Position = 1;
			this.vbox3.Add (this.hbox9);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox9]));
			w28.Position = 2;
			w28.Expand = false;
			w28.Fill = false;
			this.vbox1.Add (this.vbox3);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.vbox3]));
			w29.Position = 1;
			w29.Expand = false;
			w29.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox10 = new global::Gtk.HBox ();
			this.hbox10.Name = "hbox10";
			this.hbox10.Spacing = 6;
			// Container child hbox10.Gtk.Box+BoxChild
			this.hbox41 = new global::Gtk.HBox ();
			this.hbox41.Name = "hbox41";
			this.hbox41.Spacing = 6;
			// Container child hbox41.Gtk.Box+BoxChild
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Director/Author (Review)");
			this.hbox41.Add (this.label6);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox41 [this.label6]));
			w30.Position = 0;
			w30.Expand = false;
			w30.Fill = false;
			// Container child hbox41.Gtk.Box+BoxChild
			this.director = new global::Gtk.Entry ();
			this.director.CanFocus = true;
			this.director.Name = "director";
			this.director.IsEditable = true;
			this.director.InvisibleChar = '•';
			this.hbox41.Add (this.director);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.hbox41 [this.director]));
			w31.Position = 1;
			this.hbox10.Add (this.hbox41);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.hbox41]));
			w32.Position = 0;
			// Container child hbox10.Gtk.Box+BoxChild
			this.label11 = new global::Gtk.Label ();
			this.label11.Name = "label11";
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("Corporate Author");
			this.hbox10.Add (this.label11);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.label11]));
			w33.Position = 1;
			w33.Expand = false;
			w33.Fill = false;
			// Container child hbox10.Gtk.Box+BoxChild
			this.corpauth = new global::Gtk.Entry ();
			this.corpauth.CanFocus = true;
			this.corpauth.Name = "corpauth";
			this.corpauth.IsEditable = true;
			this.corpauth.InvisibleChar = '•';
			this.hbox10.Add (this.corpauth);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.corpauth]));
			w34.Position = 2;
			this.vbox2.Add (this.hbox10);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox10]));
			w35.Position = 0;
			w35.Expand = false;
			w35.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hseparator3 = new global::Gtk.HSeparator ();
			this.hseparator3.Name = "hseparator3";
			this.vbox2.Add (this.hseparator3);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hseparator3]));
			w36.Position = 1;
			w36.Expand = false;
			w36.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hseparator4 = new global::Gtk.HSeparator ();
			this.hseparator4.Name = "hseparator4";
			this.vbox2.Add (this.hseparator4);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hseparator4]));
			w37.Position = 2;
			w37.Expand = false;
			w37.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox11 = new global::Gtk.HBox ();
			this.hbox11.Name = "hbox11";
			this.hbox11.Spacing = 6;
			// Container child hbox11.Gtk.Box+BoxChild
			this.label12 = new global::Gtk.Label ();
			this.label12.Name = "label12";
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString ("Publisher");
			this.hbox11.Add (this.label12);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.label12]));
			w38.Position = 0;
			w38.Expand = false;
			w38.Fill = false;
			// Container child hbox11.Gtk.Box+BoxChild
			this.hbox13 = new global::Gtk.HBox ();
			this.hbox13.Name = "hbox13";
			this.hbox13.Spacing = 6;
			// Container child hbox13.Gtk.Box+BoxChild
			this.pub = new global::Gtk.Entry ();
			this.pub.CanFocus = true;
			this.pub.Name = "pub";
			this.pub.IsEditable = true;
			this.pub.InvisibleChar = '•';
			this.hbox13.Add (this.pub);
			global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.pub]));
			w39.Position = 0;
			// Container child hbox13.Gtk.Box+BoxChild
			this.label13 = new global::Gtk.Label ();
			this.label13.Name = "label13";
			this.label13.LabelProp = global::Mono.Unix.Catalog.GetString ("City");
			this.hbox13.Add (this.label13);
			global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.label13]));
			w40.Position = 1;
			w40.Expand = false;
			w40.Fill = false;
			// Container child hbox13.Gtk.Box+BoxChild
			this.city = new global::Gtk.Entry ();
			this.city.CanFocus = true;
			this.city.Name = "city";
			this.city.IsEditable = true;
			this.city.InvisibleChar = '•';
			this.hbox13.Add (this.city);
			global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.city]));
			w41.Position = 2;
			this.hbox11.Add (this.hbox13);
			global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.hbox13]));
			w42.Position = 1;
			// Container child hbox11.Gtk.Box+BoxChild
			this.hbox12 = new global::Gtk.HBox ();
			this.hbox12.Name = "hbox12";
			this.hbox12.Spacing = 6;
			// Container child hbox12.Gtk.Box+BoxChild
			this.label14 = new global::Gtk.Label ();
			this.label14.Name = "label14";
			this.label14.LabelProp = global::Mono.Unix.Catalog.GetString ("Country");
			this.hbox12.Add (this.label14);
			global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.label14]));
			w43.Position = 0;
			w43.Expand = false;
			w43.Fill = false;
			// Container child hbox12.Gtk.Box+BoxChild
			this.country = new global::Gtk.Entry ();
			this.country.CanFocus = true;
			this.country.Name = "country";
			this.country.IsEditable = true;
			this.country.InvisibleChar = '•';
			this.hbox12.Add (this.country);
			global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.country]));
			w44.Position = 1;
			this.hbox11.Add (this.hbox12);
			global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.hbox12]));
			w45.Position = 2;
			this.vbox2.Add (this.hbox11);
			global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox11]));
			w46.Position = 3;
			w46.Expand = false;
			w46.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox15 = new global::Gtk.HBox ();
			this.hbox15.Name = "hbox15";
			this.hbox15.Spacing = 6;
			// Container child hbox15.Gtk.Box+BoxChild
			this.label15 = new global::Gtk.Label ();
			this.label15.Name = "label15";
			this.label15.LabelProp = global::Mono.Unix.Catalog.GetString ("Journal/Mag/Newspaper/Blog");
			this.hbox15.Add (this.label15);
			global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.hbox15 [this.label15]));
			w47.Position = 0;
			w47.Expand = false;
			w47.Fill = false;
			// Container child hbox15.Gtk.Box+BoxChild
			this.hbox17 = new global::Gtk.HBox ();
			this.hbox17.Name = "hbox17";
			this.hbox17.Spacing = 6;
			// Container child hbox17.Gtk.Box+BoxChild
			this.journal = new global::Gtk.Entry ();
			this.journal.CanFocus = true;
			this.journal.Name = "journal";
			this.journal.IsEditable = true;
			this.journal.InvisibleChar = '•';
			this.hbox17.Add (this.journal);
			global::Gtk.Box.BoxChild w48 = ((global::Gtk.Box.BoxChild)(this.hbox17 [this.journal]));
			w48.Position = 0;
			// Container child hbox17.Gtk.Box+BoxChild
			this.label16 = new global::Gtk.Label ();
			this.label16.Name = "label16";
			this.label16.LabelProp = global::Mono.Unix.Catalog.GetString ("Ariticle");
			this.hbox17.Add (this.label16);
			global::Gtk.Box.BoxChild w49 = ((global::Gtk.Box.BoxChild)(this.hbox17 [this.label16]));
			w49.Position = 1;
			w49.Expand = false;
			w49.Fill = false;
			// Container child hbox17.Gtk.Box+BoxChild
			this.article = new global::Gtk.Entry ();
			this.article.CanFocus = true;
			this.article.Name = "article";
			this.article.IsEditable = true;
			this.article.InvisibleChar = '•';
			this.hbox17.Add (this.article);
			global::Gtk.Box.BoxChild w50 = ((global::Gtk.Box.BoxChild)(this.hbox17 [this.article]));
			w50.Position = 2;
			this.hbox15.Add (this.hbox17);
			global::Gtk.Box.BoxChild w51 = ((global::Gtk.Box.BoxChild)(this.hbox15 [this.hbox17]));
			w51.Position = 1;
			// Container child hbox15.Gtk.Box+BoxChild
			this.hbox16 = new global::Gtk.HBox ();
			this.hbox16.Name = "hbox16";
			this.hbox16.Spacing = 6;
			// Container child hbox16.Gtk.Box+BoxChild
			this.label19 = new global::Gtk.Label ();
			this.label19.Name = "label19";
			this.label19.LabelProp = global::Mono.Unix.Catalog.GetString ("Volume");
			this.hbox16.Add (this.label19);
			global::Gtk.Box.BoxChild w52 = ((global::Gtk.Box.BoxChild)(this.hbox16 [this.label19]));
			w52.Position = 0;
			w52.Expand = false;
			w52.Fill = false;
			// Container child hbox16.Gtk.Box+BoxChild
			this.hbox18 = new global::Gtk.HBox ();
			this.hbox18.Name = "hbox18";
			this.hbox18.Spacing = 6;
			// Container child hbox18.Gtk.Box+BoxChild
			this.volume = new global::Gtk.Entry ();
			this.volume.CanFocus = true;
			this.volume.Name = "volume";
			this.volume.IsEditable = true;
			this.volume.InvisibleChar = '•';
			this.hbox18.Add (this.volume);
			global::Gtk.Box.BoxChild w53 = ((global::Gtk.Box.BoxChild)(this.hbox18 [this.volume]));
			w53.Position = 0;
			// Container child hbox18.Gtk.Box+BoxChild
			this.label20 = new global::Gtk.Label ();
			this.label20.Name = "label20";
			this.label20.LabelProp = global::Mono.Unix.Catalog.GetString ("Issue");
			this.hbox18.Add (this.label20);
			global::Gtk.Box.BoxChild w54 = ((global::Gtk.Box.BoxChild)(this.hbox18 [this.label20]));
			w54.Position = 1;
			w54.Expand = false;
			w54.Fill = false;
			// Container child hbox18.Gtk.Box+BoxChild
			this.issue = new global::Gtk.Entry ();
			this.issue.CanFocus = true;
			this.issue.Name = "issue";
			this.issue.IsEditable = true;
			this.issue.InvisibleChar = '•';
			this.hbox18.Add (this.issue);
			global::Gtk.Box.BoxChild w55 = ((global::Gtk.Box.BoxChild)(this.hbox18 [this.issue]));
			w55.Position = 2;
			this.hbox16.Add (this.hbox18);
			global::Gtk.Box.BoxChild w56 = ((global::Gtk.Box.BoxChild)(this.hbox16 [this.hbox18]));
			w56.Position = 1;
			this.hbox15.Add (this.hbox16);
			global::Gtk.Box.BoxChild w57 = ((global::Gtk.Box.BoxChild)(this.hbox15 [this.hbox16]));
			w57.Position = 2;
			this.vbox4.Add (this.hbox15);
			global::Gtk.Box.BoxChild w58 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox15]));
			w58.Position = 0;
			w58.Expand = false;
			w58.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hseparator2 = new global::Gtk.HSeparator ();
			this.hseparator2.Name = "hseparator2";
			this.vbox4.Add (this.hseparator2);
			global::Gtk.Box.BoxChild w59 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hseparator2]));
			w59.Position = 1;
			w59.Expand = false;
			w59.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.vbox6 = new global::Gtk.VBox ();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox19 = new global::Gtk.HBox ();
			this.hbox19.Name = "hbox19";
			this.hbox19.Spacing = 6;
			// Container child hbox19.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("ISSN");
			this.hbox19.Add (this.label1);
			global::Gtk.Box.BoxChild w60 = ((global::Gtk.Box.BoxChild)(this.hbox19 [this.label1]));
			w60.Position = 0;
			w60.Expand = false;
			// Container child hbox19.Gtk.Box+BoxChild
			this.issn = new global::Gtk.Entry ();
			this.issn.CanFocus = true;
			this.issn.Name = "issn";
			this.issn.IsEditable = true;
			this.issn.InvisibleChar = '•';
			this.hbox19.Add (this.issn);
			global::Gtk.Box.BoxChild w61 = ((global::Gtk.Box.BoxChild)(this.hbox19 [this.issn]));
			w61.Position = 1;
			this.vbox6.Add (this.hbox19);
			global::Gtk.Box.BoxChild w62 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox19]));
			w62.Position = 0;
			w62.Expand = false;
			w62.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox20 = new global::Gtk.HBox ();
			this.hbox20.Name = "hbox20";
			this.hbox20.Spacing = 6;
			// Container child hbox20.Gtk.Box+BoxChild
			this.label17 = new global::Gtk.Label ();
			this.label17.Name = "label17";
			this.label17.LabelProp = global::Mono.Unix.Catalog.GetString ("ISBN");
			this.hbox20.Add (this.label17);
			global::Gtk.Box.BoxChild w63 = ((global::Gtk.Box.BoxChild)(this.hbox20 [this.label17]));
			w63.Position = 0;
			w63.Expand = false;
			w63.Fill = false;
			// Container child hbox20.Gtk.Box+BoxChild
			this.isbn = new global::Gtk.Entry ();
			this.isbn.CanFocus = true;
			this.isbn.Name = "isbn";
			this.isbn.IsEditable = true;
			this.isbn.InvisibleChar = '•';
			this.hbox20.Add (this.isbn);
			global::Gtk.Box.BoxChild w64 = ((global::Gtk.Box.BoxChild)(this.hbox20 [this.isbn]));
			w64.Position = 1;
			this.vbox6.Add (this.hbox20);
			global::Gtk.Box.BoxChild w65 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox20]));
			w65.Position = 1;
			w65.Expand = false;
			w65.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox21 = new global::Gtk.HBox ();
			this.hbox21.Name = "hbox21";
			this.hbox21.Spacing = 6;
			// Container child hbox21.Gtk.Box+BoxChild
			this.label18 = new global::Gtk.Label ();
			this.label18.Name = "label18";
			this.label18.LabelProp = global::Mono.Unix.Catalog.GetString ("Library Of Congress Number");
			this.hbox21.Add (this.label18);
			global::Gtk.Box.BoxChild w66 = ((global::Gtk.Box.BoxChild)(this.hbox21 [this.label18]));
			w66.Position = 0;
			w66.Expand = false;
			w66.Fill = false;
			// Container child hbox21.Gtk.Box+BoxChild
			this.loc = new global::Gtk.Entry ();
			this.loc.CanFocus = true;
			this.loc.Name = "loc";
			this.loc.IsEditable = true;
			this.loc.InvisibleChar = '•';
			this.hbox21.Add (this.loc);
			global::Gtk.Box.BoxChild w67 = ((global::Gtk.Box.BoxChild)(this.hbox21 [this.loc]));
			w67.Position = 1;
			// Container child hbox21.Gtk.Box+BoxChild
			this.hbox44 = new global::Gtk.HBox ();
			this.hbox44.Name = "hbox44";
			this.hbox44.Spacing = 6;
			// Container child hbox44.Gtk.Box+BoxChild
			this.label38 = new global::Gtk.Label ();
			this.label38.Name = "label38";
			this.label38.LabelProp = global::Mono.Unix.Catalog.GetString ("runtime");
			this.hbox44.Add (this.label38);
			global::Gtk.Box.BoxChild w68 = ((global::Gtk.Box.BoxChild)(this.hbox44 [this.label38]));
			w68.Position = 0;
			w68.Expand = false;
			w68.Fill = false;
			// Container child hbox44.Gtk.Box+BoxChild
			this.runtime = new global::Gtk.Entry ();
			this.runtime.CanFocus = true;
			this.runtime.Name = "runtime";
			this.runtime.IsEditable = true;
			this.runtime.InvisibleChar = '•';
			this.hbox44.Add (this.runtime);
			global::Gtk.Box.BoxChild w69 = ((global::Gtk.Box.BoxChild)(this.hbox44 [this.runtime]));
			w69.Position = 1;
			this.hbox21.Add (this.hbox44);
			global::Gtk.Box.BoxChild w70 = ((global::Gtk.Box.BoxChild)(this.hbox21 [this.hbox44]));
			w70.Position = 2;
			this.vbox6.Add (this.hbox21);
			global::Gtk.Box.BoxChild w71 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox21]));
			w71.Position = 2;
			w71.Expand = false;
			w71.Fill = false;
			this.vbox4.Add (this.vbox6);
			global::Gtk.Box.BoxChild w72 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.vbox6]));
			w72.Position = 2;
			w72.Expand = false;
			w72.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox22 = new global::Gtk.HBox ();
			this.hbox22.Name = "hbox22";
			this.hbox22.Spacing = 6;
			// Container child hbox22.Gtk.Box+BoxChild
			this.label21 = new global::Gtk.Label ();
			this.label21.Name = "label21";
			this.label21.LabelProp = global::Mono.Unix.Catalog.GetString ("DOI");
			this.hbox22.Add (this.label21);
			global::Gtk.Box.BoxChild w73 = ((global::Gtk.Box.BoxChild)(this.hbox22 [this.label21]));
			w73.Position = 0;
			w73.Expand = false;
			w73.Fill = false;
			// Container child hbox22.Gtk.Box+BoxChild
			this.doi = new global::Gtk.Entry ();
			this.doi.CanFocus = true;
			this.doi.Name = "doi";
			this.doi.IsEditable = true;
			this.doi.InvisibleChar = '•';
			this.hbox22.Add (this.doi);
			global::Gtk.Box.BoxChild w74 = ((global::Gtk.Box.BoxChild)(this.hbox22 [this.doi]));
			w74.Position = 1;
			this.vbox5.Add (this.hbox22);
			global::Gtk.Box.BoxChild w75 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.hbox22]));
			w75.Position = 0;
			w75.Expand = false;
			w75.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox23 = new global::Gtk.HBox ();
			this.hbox23.Name = "hbox23";
			this.hbox23.Spacing = 6;
			// Container child hbox23.Gtk.Box+BoxChild
			this.label22 = new global::Gtk.Label ();
			this.label22.Name = "label22";
			this.label22.LabelProp = global::Mono.Unix.Catalog.GetString ("URL");
			this.hbox23.Add (this.label22);
			global::Gtk.Box.BoxChild w76 = ((global::Gtk.Box.BoxChild)(this.hbox23 [this.label22]));
			w76.Position = 0;
			w76.Expand = false;
			w76.Fill = false;
			// Container child hbox23.Gtk.Box+BoxChild
			this.url = new global::Gtk.Entry ();
			this.url.CanFocus = true;
			this.url.Name = "url";
			this.url.IsEditable = true;
			this.url.InvisibleChar = '•';
			this.hbox23.Add (this.url);
			global::Gtk.Box.BoxChild w77 = ((global::Gtk.Box.BoxChild)(this.hbox23 [this.url]));
			w77.Position = 1;
			this.vbox5.Add (this.hbox23);
			global::Gtk.Box.BoxChild w78 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.hbox23]));
			w78.Position = 1;
			w78.Expand = false;
			w78.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.vbox7 = new global::Gtk.VBox ();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.label23 = new global::Gtk.Label ();
			this.label23.Name = "label23";
			this.label23.LabelProp = global::Mono.Unix.Catalog.GetString ("Medium");
			this.hbox3.Add (this.label23);
			global::Gtk.Box.BoxChild w79 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.label23]));
			w79.Position = 0;
			w79.Expand = false;
			w79.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.medium = new global::Gtk.Entry ();
			this.medium.CanFocus = true;
			this.medium.Name = "medium";
			this.medium.IsEditable = true;
			this.medium.InvisibleChar = '•';
			this.hbox3.Add (this.medium);
			global::Gtk.Box.BoxChild w80 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.medium]));
			w80.Position = 1;
			this.vbox7.Add (this.hbox3);
			global::Gtk.Box.BoxChild w81 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hbox3]));
			w81.Position = 0;
			w81.Expand = false;
			w81.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.vbox8 = new global::Gtk.VBox ();
			this.vbox8.Name = "vbox8";
			this.vbox8.Spacing = 6;
			// Container child vbox8.Gtk.Box+BoxChild
			this.hbox24 = new global::Gtk.HBox ();
			this.hbox24.Name = "hbox24";
			this.hbox24.Spacing = 6;
			// Container child hbox24.Gtk.Box+BoxChild
			this.label24 = new global::Gtk.Label ();
			this.label24.Name = "label24";
			this.label24.LabelProp = global::Mono.Unix.Catalog.GetString ("Edition");
			this.hbox24.Add (this.label24);
			global::Gtk.Box.BoxChild w82 = ((global::Gtk.Box.BoxChild)(this.hbox24 [this.label24]));
			w82.Position = 0;
			w82.Expand = false;
			w82.Fill = false;
			// Container child hbox24.Gtk.Box+BoxChild
			this.edition = new global::Gtk.Entry ();
			this.edition.CanFocus = true;
			this.edition.Name = "edition";
			this.edition.IsEditable = true;
			this.edition.InvisibleChar = '•';
			this.hbox24.Add (this.edition);
			global::Gtk.Box.BoxChild w83 = ((global::Gtk.Box.BoxChild)(this.hbox24 [this.edition]));
			w83.Position = 1;
			this.vbox8.Add (this.hbox24);
			global::Gtk.Box.BoxChild w84 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.hbox24]));
			w84.Position = 0;
			w84.Expand = false;
			w84.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.hbox25 = new global::Gtk.HBox ();
			this.hbox25.Name = "hbox25";
			this.hbox25.Spacing = 6;
			// Container child hbox25.Gtk.Box+BoxChild
			this.label25 = new global::Gtk.Label ();
			this.label25.Name = "label25";
			this.label25.LabelProp = global::Mono.Unix.Catalog.GetString ("Institution");
			this.hbox25.Add (this.label25);
			global::Gtk.Box.BoxChild w85 = ((global::Gtk.Box.BoxChild)(this.hbox25 [this.label25]));
			w85.Position = 0;
			w85.Expand = false;
			w85.Fill = false;
			// Container child hbox25.Gtk.Box+BoxChild
			this.institution = new global::Gtk.Entry ();
			this.institution.CanFocus = true;
			this.institution.Name = "institution";
			this.institution.IsEditable = true;
			this.institution.InvisibleChar = '•';
			this.hbox25.Add (this.institution);
			global::Gtk.Box.BoxChild w86 = ((global::Gtk.Box.BoxChild)(this.hbox25 [this.institution]));
			w86.Position = 1;
			this.vbox8.Add (this.hbox25);
			global::Gtk.Box.BoxChild w87 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.hbox25]));
			w87.Position = 1;
			w87.Expand = false;
			w87.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.vbox9 = new global::Gtk.VBox ();
			this.vbox9.Name = "vbox9";
			this.vbox9.Spacing = 6;
			// Container child vbox9.Gtk.Box+BoxChild
			this.hbox26 = new global::Gtk.HBox ();
			this.hbox26.Name = "hbox26";
			this.hbox26.Spacing = 6;
			// Container child hbox26.Gtk.Box+BoxChild
			this.label26 = new global::Gtk.Label ();
			this.label26.Name = "label26";
			this.label26.LabelProp = global::Mono.Unix.Catalog.GetString ("Publication Type");
			this.hbox26.Add (this.label26);
			global::Gtk.Box.BoxChild w88 = ((global::Gtk.Box.BoxChild)(this.hbox26 [this.label26]));
			w88.Position = 0;
			w88.Expand = false;
			w88.Fill = false;
			// Container child hbox26.Gtk.Box+BoxChild
			this.pubtype = new global::Gtk.Entry ();
			this.pubtype.CanFocus = true;
			this.pubtype.Name = "pubtype";
			this.pubtype.IsEditable = true;
			this.pubtype.InvisibleChar = '•';
			this.hbox26.Add (this.pubtype);
			global::Gtk.Box.BoxChild w89 = ((global::Gtk.Box.BoxChild)(this.hbox26 [this.pubtype]));
			w89.Position = 1;
			this.vbox9.Add (this.hbox26);
			global::Gtk.Box.BoxChild w90 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.hbox26]));
			w90.Position = 0;
			w90.Expand = false;
			w90.Fill = false;
			// Container child vbox9.Gtk.Box+BoxChild
			this.hbox27 = new global::Gtk.HBox ();
			this.hbox27.Name = "hbox27";
			this.hbox27.Spacing = 6;
			// Container child hbox27.Gtk.Box+BoxChild
			this.label27 = new global::Gtk.Label ();
			this.label27.Name = "label27";
			this.label27.LabelProp = global::Mono.Unix.Catalog.GetString ("Chapter / Section");
			this.hbox27.Add (this.label27);
			global::Gtk.Box.BoxChild w91 = ((global::Gtk.Box.BoxChild)(this.hbox27 [this.label27]));
			w91.Position = 0;
			w91.Expand = false;
			w91.Fill = false;
			// Container child hbox27.Gtk.Box+BoxChild
			this.chapter = new global::Gtk.Entry ();
			this.chapter.CanFocus = true;
			this.chapter.Name = "chapter";
			this.chapter.IsEditable = true;
			this.chapter.InvisibleChar = '•';
			this.hbox27.Add (this.chapter);
			global::Gtk.Box.BoxChild w92 = ((global::Gtk.Box.BoxChild)(this.hbox27 [this.chapter]));
			w92.Position = 1;
			this.vbox9.Add (this.hbox27);
			global::Gtk.Box.BoxChild w93 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.hbox27]));
			w93.Position = 1;
			w93.Expand = false;
			w93.Fill = false;
			// Container child vbox9.Gtk.Box+BoxChild
			this.vbox10 = new global::Gtk.VBox ();
			this.vbox10.Name = "vbox10";
			this.vbox10.Spacing = 6;
			// Container child vbox10.Gtk.Box+BoxChild
			this.hbox28 = new global::Gtk.HBox ();
			this.hbox28.Name = "hbox28";
			this.hbox28.Spacing = 6;
			// Container child hbox28.Gtk.Box+BoxChild
			this.label28 = new global::Gtk.Label ();
			this.label28.Name = "label28";
			this.label28.LabelProp = global::Mono.Unix.Catalog.GetString ("Page(s)");
			this.hbox28.Add (this.label28);
			global::Gtk.Box.BoxChild w94 = ((global::Gtk.Box.BoxChild)(this.hbox28 [this.label28]));
			w94.Position = 0;
			w94.Expand = false;
			w94.Fill = false;
			// Container child hbox28.Gtk.Box+BoxChild
			this.pages = new global::Gtk.Entry ();
			this.pages.CanFocus = true;
			this.pages.Name = "pages";
			this.pages.IsEditable = true;
			this.pages.InvisibleChar = '•';
			this.hbox28.Add (this.pages);
			global::Gtk.Box.BoxChild w95 = ((global::Gtk.Box.BoxChild)(this.hbox28 [this.pages]));
			w95.Position = 1;
			this.vbox10.Add (this.hbox28);
			global::Gtk.Box.BoxChild w96 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.hbox28]));
			w96.Position = 0;
			w96.Expand = false;
			w96.Fill = false;
			// Container child vbox10.Gtk.Box+BoxChild
			this.hbox29 = new global::Gtk.HBox ();
			this.hbox29.Name = "hbox29";
			this.hbox29.Spacing = 6;
			// Container child hbox29.Gtk.Box+BoxChild
			this.Series = new global::Gtk.Label ();
			this.Series.Name = "Series";
			this.Series.LabelProp = global::Mono.Unix.Catalog.GetString ("Series");
			this.hbox29.Add (this.Series);
			global::Gtk.Box.BoxChild w97 = ((global::Gtk.Box.BoxChild)(this.hbox29 [this.Series]));
			w97.Position = 0;
			w97.Expand = false;
			w97.Fill = false;
			// Container child hbox29.Gtk.Box+BoxChild
			this.series = new global::Gtk.Entry ();
			this.series.CanFocus = true;
			this.series.Name = "series";
			this.series.IsEditable = true;
			this.series.InvisibleChar = '•';
			this.hbox29.Add (this.series);
			global::Gtk.Box.BoxChild w98 = ((global::Gtk.Box.BoxChild)(this.hbox29 [this.series]));
			w98.Position = 1;
			this.vbox10.Add (this.hbox29);
			global::Gtk.Box.BoxChild w99 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.hbox29]));
			w99.Position = 1;
			w99.Expand = false;
			w99.Fill = false;
			// Container child vbox10.Gtk.Box+BoxChild
			this.vbox11 = new global::Gtk.VBox ();
			this.vbox11.Name = "vbox11";
			this.vbox11.Spacing = 6;
			// Container child vbox11.Gtk.Box+BoxChild
			this.hbox14 = new global::Gtk.HBox ();
			this.hbox14.Name = "hbox14";
			this.hbox14.Spacing = 6;
			// Container child hbox14.Gtk.Box+BoxChild
			this.label30 = new global::Gtk.Label ();
			this.label30.Name = "label30";
			this.label30.LabelProp = global::Mono.Unix.Catalog.GetString ("Organization");
			this.hbox14.Add (this.label30);
			global::Gtk.Box.BoxChild w100 = ((global::Gtk.Box.BoxChild)(this.hbox14 [this.label30]));
			w100.Position = 0;
			w100.Expand = false;
			w100.Fill = false;
			// Container child hbox14.Gtk.Box+BoxChild
			this.org = new global::Gtk.Entry ();
			this.org.CanFocus = true;
			this.org.Name = "org";
			this.org.IsEditable = true;
			this.org.InvisibleChar = '•';
			this.hbox14.Add (this.org);
			global::Gtk.Box.BoxChild w101 = ((global::Gtk.Box.BoxChild)(this.hbox14 [this.org]));
			w101.Position = 1;
			this.vbox11.Add (this.hbox14);
			global::Gtk.Box.BoxChild w102 = ((global::Gtk.Box.BoxChild)(this.vbox11 [this.hbox14]));
			w102.Position = 0;
			w102.Expand = false;
			w102.Fill = false;
			// Container child vbox11.Gtk.Box+BoxChild
			this.hbox30 = new global::Gtk.HBox ();
			this.hbox30.Name = "hbox30";
			this.hbox30.Spacing = 6;
			// Container child hbox30.Gtk.Box+BoxChild
			this.label31 = new global::Gtk.Label ();
			this.label31.Name = "label31";
			this.label31.LabelProp = global::Mono.Unix.Catalog.GetString ("University");
			this.hbox30.Add (this.label31);
			global::Gtk.Box.BoxChild w103 = ((global::Gtk.Box.BoxChild)(this.hbox30 [this.label31]));
			w103.Position = 0;
			w103.Expand = false;
			w103.Fill = false;
			// Container child hbox30.Gtk.Box+BoxChild
			this.university = new global::Gtk.Entry ();
			this.university.CanFocus = true;
			this.university.Name = "university";
			this.university.IsEditable = true;
			this.university.InvisibleChar = '•';
			this.hbox30.Add (this.university);
			global::Gtk.Box.BoxChild w104 = ((global::Gtk.Box.BoxChild)(this.hbox30 [this.university]));
			w104.Position = 1;
			this.vbox11.Add (this.hbox30);
			global::Gtk.Box.BoxChild w105 = ((global::Gtk.Box.BoxChild)(this.vbox11 [this.hbox30]));
			w105.Position = 1;
			w105.Expand = false;
			w105.Fill = false;
			// Container child vbox11.Gtk.Box+BoxChild
			this.vbox12 = new global::Gtk.VBox ();
			this.vbox12.Name = "vbox12";
			this.vbox12.Spacing = 6;
			// Container child vbox12.Gtk.Box+BoxChild
			this.hbox31 = new global::Gtk.HBox ();
			this.hbox31.Name = "hbox31";
			this.hbox31.Spacing = 6;
			// Container child hbox31.Gtk.Box+BoxChild
			this.label32 = new global::Gtk.Label ();
			this.label32.Name = "label32";
			this.label32.LabelProp = global::Mono.Unix.Catalog.GetString ("Editor");
			this.hbox31.Add (this.label32);
			global::Gtk.Box.BoxChild w106 = ((global::Gtk.Box.BoxChild)(this.hbox31 [this.label32]));
			w106.Position = 0;
			w106.Expand = false;
			w106.Fill = false;
			// Container child hbox31.Gtk.Box+BoxChild
			this.editor = new global::Gtk.Entry ();
			this.editor.CanFocus = true;
			this.editor.Name = "editor";
			this.editor.IsEditable = true;
			this.editor.InvisibleChar = '•';
			this.hbox31.Add (this.editor);
			global::Gtk.Box.BoxChild w107 = ((global::Gtk.Box.BoxChild)(this.hbox31 [this.editor]));
			w107.Position = 1;
			this.vbox12.Add (this.hbox31);
			global::Gtk.Box.BoxChild w108 = ((global::Gtk.Box.BoxChild)(this.vbox12 [this.hbox31]));
			w108.Position = 0;
			w108.Expand = false;
			w108.Fill = false;
			// Container child vbox12.Gtk.Box+BoxChild
			this.hbox32 = new global::Gtk.HBox ();
			this.hbox32.Name = "hbox32";
			this.hbox32.Spacing = 6;
			// Container child hbox32.Gtk.Box+BoxChild
			this.label33 = new global::Gtk.Label ();
			this.label33.Name = "label33";
			this.label33.LabelProp = global::Mono.Unix.Catalog.GetString ("Translator");
			this.hbox32.Add (this.label33);
			global::Gtk.Box.BoxChild w109 = ((global::Gtk.Box.BoxChild)(this.hbox32 [this.label33]));
			w109.Position = 0;
			w109.Expand = false;
			w109.Fill = false;
			// Container child hbox32.Gtk.Box+BoxChild
			this.translator = new global::Gtk.Entry ();
			this.translator.CanFocus = true;
			this.translator.Name = "translator";
			this.translator.IsEditable = true;
			this.translator.InvisibleChar = '•';
			this.hbox32.Add (this.translator);
			global::Gtk.Box.BoxChild w110 = ((global::Gtk.Box.BoxChild)(this.hbox32 [this.translator]));
			w110.Position = 1;
			this.vbox12.Add (this.hbox32);
			global::Gtk.Box.BoxChild w111 = ((global::Gtk.Box.BoxChild)(this.vbox12 [this.hbox32]));
			w111.Position = 1;
			w111.Expand = false;
			w111.Fill = false;
			// Container child vbox12.Gtk.Box+BoxChild
			this.hbox33 = new global::Gtk.HBox ();
			this.hbox33.Name = "hbox33";
			this.hbox33.Spacing = 6;
			// Container child hbox33.Gtk.Box+BoxChild
			this.vbox13 = new global::Gtk.VBox ();
			this.vbox13.Name = "vbox13";
			this.vbox13.Spacing = 6;
			// Container child vbox13.Gtk.Box+BoxChild
			this.hbox34 = new global::Gtk.HBox ();
			this.hbox34.Name = "hbox34";
			this.hbox34.Spacing = 6;
			// Container child hbox34.Gtk.Box+BoxChild
			this.label34 = new global::Gtk.Label ();
			this.label34.Name = "label34";
			this.label34.LabelProp = global::Mono.Unix.Catalog.GetString ("EtCetera");
			this.hbox34.Add (this.label34);
			global::Gtk.Box.BoxChild w112 = ((global::Gtk.Box.BoxChild)(this.hbox34 [this.label34]));
			w112.Position = 0;
			w112.Expand = false;
			w112.Fill = false;
			// Container child hbox34.Gtk.Box+BoxChild
			this.etcetera = new global::Gtk.Entry ();
			this.etcetera.CanFocus = true;
			this.etcetera.Name = "etcetera";
			this.etcetera.IsEditable = true;
			this.etcetera.InvisibleChar = '•';
			this.hbox34.Add (this.etcetera);
			global::Gtk.Box.BoxChild w113 = ((global::Gtk.Box.BoxChild)(this.hbox34 [this.etcetera]));
			w113.Position = 1;
			this.vbox13.Add (this.hbox34);
			global::Gtk.Box.BoxChild w114 = ((global::Gtk.Box.BoxChild)(this.vbox13 [this.hbox34]));
			w114.Position = 0;
			w114.Expand = false;
			w114.Fill = false;
			// Container child vbox13.Gtk.Box+BoxChild
			this.hbox35 = new global::Gtk.HBox ();
			this.hbox35.Name = "hbox35";
			this.hbox35.Spacing = 6;
			// Container child hbox35.Gtk.Box+BoxChild
			this.label35 = new global::Gtk.Label ();
			this.label35.Name = "label35";
			this.label35.LabelProp = global::Mono.Unix.Catalog.GetString ("Annotation");
			this.hbox35.Add (this.label35);
			global::Gtk.Box.BoxChild w115 = ((global::Gtk.Box.BoxChild)(this.hbox35 [this.label35]));
			w115.Position = 0;
			w115.Expand = false;
			w115.Fill = false;
			// Container child hbox35.Gtk.Box+BoxChild
			this.annotation2 = new global::Gtk.ScrolledWindow ();
			this.annotation2.Name = "annotation2";
			this.annotation2.HscrollbarPolicy = ((global::Gtk.PolicyType)(2));
			this.annotation2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child annotation2.Gtk.Container+ContainerChild
			this.annotation = new global::Gtk.TextView ();
			this.annotation.Buffer.Text = "\t\t";
			this.annotation.HeightRequest = 375;
			this.annotation.CanFocus = true;
			this.annotation.Name = "annotation";
			this.annotation.WrapMode = ((global::Gtk.WrapMode)(2));
			this.annotation2.Add (this.annotation);
			this.hbox35.Add (this.annotation2);
			global::Gtk.Box.BoxChild w117 = ((global::Gtk.Box.BoxChild)(this.hbox35 [this.annotation2]));
			w117.Position = 1;
			this.vbox13.Add (this.hbox35);
			global::Gtk.Box.BoxChild w118 = ((global::Gtk.Box.BoxChild)(this.vbox13 [this.hbox35]));
			w118.Position = 1;
			w118.Expand = false;
			w118.Fill = false;
			// Container child vbox13.Gtk.Box+BoxChild
			this.hbox36 = new global::Gtk.HBox ();
			this.hbox36.Name = "hbox36";
			this.hbox36.Spacing = 6;
			// Container child hbox36.Gtk.Box+BoxChild
			this.label29 = new global::Gtk.Label ();
			this.label29.Name = "label29";
			this.label29.LabelProp = global::Mono.Unix.Catalog.GetString ("AccessDay");
			this.hbox36.Add (this.label29);
			global::Gtk.Box.BoxChild w119 = ((global::Gtk.Box.BoxChild)(this.hbox36 [this.label29]));
			w119.Position = 0;
			w119.Expand = false;
			w119.Fill = false;
			// Container child hbox36.Gtk.Box+BoxChild
			this.hbox42 = new global::Gtk.HBox ();
			this.hbox42.Name = "hbox42";
			this.hbox42.Spacing = 6;
			// Container child hbox42.Gtk.Box+BoxChild
			this.accessday = new global::Gtk.Entry ();
			this.accessday.CanFocus = true;
			this.accessday.Name = "accessday";
			this.accessday.IsEditable = true;
			this.accessday.InvisibleChar = '•';
			this.hbox42.Add (this.accessday);
			global::Gtk.Box.BoxChild w120 = ((global::Gtk.Box.BoxChild)(this.hbox42 [this.accessday]));
			w120.Position = 0;
			// Container child hbox42.Gtk.Box+BoxChild
			this.label36 = new global::Gtk.Label ();
			this.label36.Name = "label36";
			this.label36.LabelProp = global::Mono.Unix.Catalog.GetString ("AccessMonth");
			this.hbox42.Add (this.label36);
			global::Gtk.Box.BoxChild w121 = ((global::Gtk.Box.BoxChild)(this.hbox42 [this.label36]));
			w121.Position = 1;
			w121.Expand = false;
			w121.Fill = false;
			// Container child hbox42.Gtk.Box+BoxChild
			this.hbox43 = new global::Gtk.HBox ();
			this.hbox43.Name = "hbox43";
			this.hbox43.Spacing = 6;
			// Container child hbox43.Gtk.Box+BoxChild
			this.accessmonth = new global::Gtk.Entry ();
			this.accessmonth.CanFocus = true;
			this.accessmonth.Name = "accessmonth";
			this.accessmonth.IsEditable = true;
			this.accessmonth.InvisibleChar = '•';
			this.hbox43.Add (this.accessmonth);
			global::Gtk.Box.BoxChild w122 = ((global::Gtk.Box.BoxChild)(this.hbox43 [this.accessmonth]));
			w122.Position = 0;
			// Container child hbox43.Gtk.Box+BoxChild
			this.label37 = new global::Gtk.Label ();
			this.label37.Name = "label37";
			this.label37.LabelProp = global::Mono.Unix.Catalog.GetString ("AcessYear");
			this.hbox43.Add (this.label37);
			global::Gtk.Box.BoxChild w123 = ((global::Gtk.Box.BoxChild)(this.hbox43 [this.label37]));
			w123.Position = 1;
			w123.Expand = false;
			w123.Fill = false;
			// Container child hbox43.Gtk.Box+BoxChild
			this.accessyear = new global::Gtk.Entry ();
			this.accessyear.CanFocus = true;
			this.accessyear.Name = "accessyear";
			this.accessyear.IsEditable = true;
			this.accessyear.InvisibleChar = '•';
			this.hbox43.Add (this.accessyear);
			global::Gtk.Box.BoxChild w124 = ((global::Gtk.Box.BoxChild)(this.hbox43 [this.accessyear]));
			w124.Position = 2;
			this.hbox42.Add (this.hbox43);
			global::Gtk.Box.BoxChild w125 = ((global::Gtk.Box.BoxChild)(this.hbox42 [this.hbox43]));
			w125.Position = 2;
			this.hbox36.Add (this.hbox42);
			global::Gtk.Box.BoxChild w126 = ((global::Gtk.Box.BoxChild)(this.hbox36 [this.hbox42]));
			w126.Position = 1;
			// Container child hbox36.Gtk.Box+BoxChild
			this.Submit = new global::Gtk.Button ();
			this.Submit.CanFocus = true;
			this.Submit.Name = "Submit";
			this.Submit.UseUnderline = true;
			this.Submit.Label = global::Mono.Unix.Catalog.GetString ("Submit");
			this.hbox36.Add (this.Submit);
			global::Gtk.Box.BoxChild w127 = ((global::Gtk.Box.BoxChild)(this.hbox36 [this.Submit]));
			w127.Position = 2;
			w127.Expand = false;
			w127.Fill = false;
			this.vbox13.Add (this.hbox36);
			global::Gtk.Box.BoxChild w128 = ((global::Gtk.Box.BoxChild)(this.vbox13 [this.hbox36]));
			w128.Position = 2;
			w128.Expand = false;
			w128.Fill = false;
			this.hbox33.Add (this.vbox13);
			global::Gtk.Box.BoxChild w129 = ((global::Gtk.Box.BoxChild)(this.hbox33 [this.vbox13]));
			w129.Position = 0;
			this.vbox12.Add (this.hbox33);
			global::Gtk.Box.BoxChild w130 = ((global::Gtk.Box.BoxChild)(this.vbox12 [this.hbox33]));
			w130.Position = 2;
			w130.Expand = false;
			w130.Fill = false;
			this.vbox11.Add (this.vbox12);
			global::Gtk.Box.BoxChild w131 = ((global::Gtk.Box.BoxChild)(this.vbox11 [this.vbox12]));
			w131.Position = 2;
			w131.Expand = false;
			w131.Fill = false;
			this.vbox10.Add (this.vbox11);
			global::Gtk.Box.BoxChild w132 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.vbox11]));
			w132.Position = 2;
			w132.Expand = false;
			w132.Fill = false;
			this.vbox9.Add (this.vbox10);
			global::Gtk.Box.BoxChild w133 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.vbox10]));
			w133.Position = 2;
			w133.Expand = false;
			w133.Fill = false;
			this.vbox8.Add (this.vbox9);
			global::Gtk.Box.BoxChild w134 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.vbox9]));
			w134.Position = 2;
			w134.Expand = false;
			w134.Fill = false;
			this.vbox7.Add (this.vbox8);
			global::Gtk.Box.BoxChild w135 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.vbox8]));
			w135.Position = 1;
			w135.Expand = false;
			w135.Fill = false;
			this.vbox5.Add (this.vbox7);
			global::Gtk.Box.BoxChild w136 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.vbox7]));
			w136.Position = 2;
			w136.Expand = false;
			w136.Fill = false;
			this.vbox4.Add (this.vbox5);
			global::Gtk.Box.BoxChild w137 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.vbox5]));
			w137.Position = 3;
			w137.Expand = false;
			w137.Fill = false;
			this.vbox2.Add (this.vbox4);
			global::Gtk.Box.BoxChild w138 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.vbox4]));
			w138.Position = 4;
			w138.Expand = false;
			w138.Fill = false;
			this.vbox1.Add (this.vbox2);
			global::Gtk.Box.BoxChild w139 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.vbox2]));
			w139.Position = 2;
			w139.Expand = false;
			w139.Fill = false;
			this.GtkAlignment.Add (this.vbox1);
			this.frame1.Add (this.GtkAlignment);
			w2.Add (this.frame1);
			this.GtkScrolledWindow.Add (w2);
			this.notebook4.Add (this.GtkScrolledWindow);
			global::Gtk.Notebook.NotebookChild w144 = ((global::Gtk.Notebook.NotebookChild)(this.notebook4 [this.GtkScrolledWindow]));
			w144.TabExpand = true;
			w144.MenuLabel = "";
			// Notebook tab
			this.Indexer = new global::Gtk.Label ();
			this.Indexer.CanDefault = true;
			this.Indexer.Name = "Indexer";
			this.Indexer.LabelProp = global::Mono.Unix.Catalog.GetString ("Indexer");
			this.notebook4.SetTabLabel (this.GtkScrolledWindow, this.Indexer);
			this.Indexer.ShowAll ();
			// Container child notebook4.Gtk.Notebook+NotebookChild
			this.vbox15 = new global::Gtk.VBox ();
			this.vbox15.Name = "vbox15";
			this.vbox15.Spacing = 6;
			// Container child vbox15.Gtk.Box+BoxChild
			this.hbox40 = new global::Gtk.HBox ();
			this.hbox40.Name = "hbox40";
			this.hbox40.Spacing = 6;
			// Container child hbox40.Gtk.Box+BoxChild
			this.refresh = new global::Gtk.Button ();
			this.refresh.CanFocus = true;
			this.refresh.Name = "refresh";
			this.refresh.UseUnderline = true;
			this.refresh.Label = global::Mono.Unix.Catalog.GetString ("Refresh");
			this.hbox40.Add (this.refresh);
			global::Gtk.Box.BoxChild w145 = ((global::Gtk.Box.BoxChild)(this.hbox40 [this.refresh]));
			w145.Position = 0;
			w145.Expand = false;
			w145.Fill = false;
			// Container child hbox40.Gtk.Box+BoxChild
			this.clear = new global::Gtk.Button ();
			this.clear.CanFocus = true;
			this.clear.Name = "clear";
			this.clear.UseUnderline = true;
			this.clear.Label = global::Mono.Unix.Catalog.GetString ("Clear Entries");
			this.hbox40.Add (this.clear);
			global::Gtk.Box.BoxChild w146 = ((global::Gtk.Box.BoxChild)(this.hbox40 [this.clear]));
			w146.Position = 1;
			w146.Expand = false;
			w146.Fill = false;
			// Container child hbox40.Gtk.Box+BoxChild
			this.fixed3 = new global::Gtk.Fixed ();
			this.fixed3.Name = "fixed3";
			this.fixed3.HasWindow = false;
			this.hbox40.Add (this.fixed3);
			global::Gtk.Box.BoxChild w147 = ((global::Gtk.Box.BoxChild)(this.hbox40 [this.fixed3]));
			w147.Position = 2;
			this.vbox15.Add (this.hbox40);
			global::Gtk.Box.BoxChild w148 = ((global::Gtk.Box.BoxChild)(this.vbox15 [this.hbox40]));
			w148.Position = 0;
			w148.Expand = false;
			w148.Fill = false;
			// Container child vbox15.Gtk.Box+BoxChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.HscrollbarPolicy = ((global::Gtk.PolicyType)(2));
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.dataview = new global::Gtk.TextView ();
			this.dataview.CanFocus = true;
			this.dataview.Name = "dataview";
			this.dataview.Editable = false;
			this.dataview.Overwrite = true;
			this.dataview.WrapMode = ((global::Gtk.WrapMode)(3));
			this.GtkScrolledWindow1.Add (this.dataview);
			this.vbox15.Add (this.GtkScrolledWindow1);
			global::Gtk.Box.BoxChild w150 = ((global::Gtk.Box.BoxChild)(this.vbox15 [this.GtkScrolledWindow1]));
			w150.Position = 1;
			this.notebook4.Add (this.vbox15);
			global::Gtk.Notebook.NotebookChild w151 = ((global::Gtk.Notebook.NotebookChild)(this.notebook4 [this.vbox15]));
			w151.Position = 1;
			// Notebook tab
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Database");
			this.notebook4.SetTabLabel (this.vbox15, this.label2);
			this.label2.ShowAll ();
			// Container child notebook4.Gtk.Notebook+NotebookChild
			this.vbox14 = new global::Gtk.VBox ();
			this.vbox14.Name = "vbox14";
			this.vbox14.Spacing = 6;
			this.vbox14.BorderWidth = ((uint)(5));
			// Container child vbox14.Gtk.Box+BoxChild
			this.hbox37 = new global::Gtk.HBox ();
			this.hbox37.Name = "hbox37";
			this.hbox37.Spacing = 6;
			// Container child hbox37.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Style");
			this.hbox37.Add (this.label3);
			global::Gtk.Box.BoxChild w152 = ((global::Gtk.Box.BoxChild)(this.hbox37 [this.label3]));
			w152.Position = 0;
			w152.Expand = false;
			w152.Fill = false;
			// Container child hbox37.Gtk.Box+BoxChild
			this.combobox1 = global::Gtk.ComboBox.NewText ();
			this.combobox1.AppendText (global::Mono.Unix.Catalog.GetString ("Select One"));
			this.combobox1.AppendText (global::Mono.Unix.Catalog.GetString ("Chicago"));
			this.combobox1.AppendText (global::Mono.Unix.Catalog.GetString ("APA"));
			this.combobox1.AppendText (global::Mono.Unix.Catalog.GetString ("MLA"));
			this.combobox1.Name = "combobox1";
			this.combobox1.Active = 0;
			this.hbox37.Add (this.combobox1);
			global::Gtk.Box.BoxChild w153 = ((global::Gtk.Box.BoxChild)(this.hbox37 [this.combobox1]));
			w153.Position = 1;
			w153.Expand = false;
			w153.Fill = false;
			// Container child hbox37.Gtk.Box+BoxChild
			this.hbox38 = new global::Gtk.HBox ();
			this.hbox38.Name = "hbox38";
			this.hbox38.Spacing = 6;
			// Container child hbox38.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Format");
			this.hbox38.Add (this.label4);
			global::Gtk.Box.BoxChild w154 = ((global::Gtk.Box.BoxChild)(this.hbox38 [this.label4]));
			w154.Position = 0;
			w154.Expand = false;
			w154.Fill = false;
			// Container child hbox38.Gtk.Box+BoxChild
			this.combobox2 = global::Gtk.ComboBox.NewText ();
			this.combobox2.AppendText (global::Mono.Unix.Catalog.GetString ("Select One"));
			this.combobox2.AppendText (global::Mono.Unix.Catalog.GetString ("Bibliography"));
			this.combobox2.AppendText (global::Mono.Unix.Catalog.GetString ("InTextCitation"));
			this.combobox2.AppendText (global::Mono.Unix.Catalog.GetString ("Footnote"));
			this.combobox2.AppendText (global::Mono.Unix.Catalog.GetString ("EndNote"));
			this.combobox2.AppendText (global::Mono.Unix.Catalog.GetString ("WorksCited"));
			this.combobox2.Name = "combobox2";
			this.combobox2.Active = 0;
			this.hbox38.Add (this.combobox2);
			global::Gtk.Box.BoxChild w155 = ((global::Gtk.Box.BoxChild)(this.hbox38 [this.combobox2]));
			w155.Position = 1;
			w155.Expand = false;
			w155.Fill = false;
			// Container child hbox38.Gtk.Box+BoxChild
			this.hbox39 = new global::Gtk.HBox ();
			this.hbox39.Name = "hbox39";
			this.hbox39.Spacing = 6;
			// Container child hbox39.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Entry");
			this.hbox39.Add (this.label5);
			global::Gtk.Box.BoxChild w156 = ((global::Gtk.Box.BoxChild)(this.hbox39 [this.label5]));
			w156.Position = 0;
			w156.Expand = false;
			w156.Fill = false;
			// Container child hbox39.Gtk.Box+BoxChild
			this.combobox3 = global::Gtk.ComboBox.NewText ();
			this.combobox3.AppendText (global::Mono.Unix.Catalog.GetString ("Select One"));
			this.combobox3.Name = "combobox3";
			this.combobox3.Active = 0;
			this.hbox39.Add (this.combobox3);
			global::Gtk.Box.BoxChild w157 = ((global::Gtk.Box.BoxChild)(this.hbox39 [this.combobox3]));
			w157.Position = 1;
			w157.Expand = false;
			w157.Fill = false;
			this.hbox38.Add (this.hbox39);
			global::Gtk.Box.BoxChild w158 = ((global::Gtk.Box.BoxChild)(this.hbox38 [this.hbox39]));
			w158.Position = 2;
			w158.Expand = false;
			w158.Fill = false;
			this.hbox37.Add (this.hbox38);
			global::Gtk.Box.BoxChild w159 = ((global::Gtk.Box.BoxChild)(this.hbox37 [this.hbox38]));
			w159.Position = 2;
			w159.Expand = false;
			w159.Fill = false;
			// Container child hbox37.Gtk.Box+BoxChild
			this.list = new global::Gtk.Button ();
			this.list.CanFocus = true;
			this.list.Name = "list";
			this.list.UseUnderline = true;
			this.list.Label = global::Mono.Unix.Catalog.GetString ("List");
			this.hbox37.Add (this.list);
			global::Gtk.Box.BoxChild w160 = ((global::Gtk.Box.BoxChild)(this.hbox37 [this.list]));
			w160.Position = 3;
			w160.Expand = false;
			w160.Fill = false;
			// Container child hbox37.Gtk.Box+BoxChild
			this.Make = new global::Gtk.Button ();
			this.Make.CanFocus = true;
			this.Make.Name = "Make";
			this.Make.UseUnderline = true;
			this.Make.Label = global::Mono.Unix.Catalog.GetString ("Make");
			this.hbox37.Add (this.Make);
			global::Gtk.Box.BoxChild w161 = ((global::Gtk.Box.BoxChild)(this.hbox37 [this.Make]));
			w161.PackType = ((global::Gtk.PackType)(1));
			w161.Position = 4;
			this.vbox14.Add (this.hbox37);
			global::Gtk.Box.BoxChild w162 = ((global::Gtk.Box.BoxChild)(this.vbox14 [this.hbox37]));
			w162.Position = 0;
			w162.Expand = false;
			w162.Fill = false;
			// Container child vbox14.Gtk.Box+BoxChild
			this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
			this.GtkScrolledWindow2.HscrollbarPolicy = ((global::Gtk.PolicyType)(2));
			this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
			this.textview2 = new global::Gtk.TextView ();
			this.textview2.CanFocus = true;
			this.textview2.Name = "textview2";
			this.textview2.Editable = false;
			this.textview2.WrapMode = ((global::Gtk.WrapMode)(3));
			this.GtkScrolledWindow2.Add (this.textview2);
			this.vbox14.Add (this.GtkScrolledWindow2);
			global::Gtk.Box.BoxChild w164 = ((global::Gtk.Box.BoxChild)(this.vbox14 [this.GtkScrolledWindow2]));
			w164.Position = 1;
			this.notebook4.Add (this.vbox14);
			global::Gtk.Notebook.NotebookChild w165 = ((global::Gtk.Notebook.NotebookChild)(this.notebook4 [this.vbox14]));
			w165.Position = 2;
			// Notebook tab
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Maker");
			this.notebook4.SetTabLabel (this.vbox14, this.label7);
			this.label7.ShowAll ();
			this.Add (this.notebook4);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 941;
			this.DefaultHeight = 590;
			this.Indexer.HasDefault = true;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.Submit.Pressed += new global::System.EventHandler (this.submitEvent);
			this.refresh.Pressed += new global::System.EventHandler (this.refreshEvent);
			this.clear.Pressed += new global::System.EventHandler (this.clearEvent);
			this.list.Pressed += new global::System.EventHandler (this.listEvent);
			this.Make.Pressed += new global::System.EventHandler (this.makeEvent);
		}
	}
}
