// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace WebBIblio {
	
	
	public partial class Default {
		
		protected System.Web.UI.HtmlControls.HtmlSelect type;
		
		protected System.Web.UI.HtmlControls.HtmlInputText day;
		
		protected System.Web.UI.HtmlControls.HtmlInputText month;
		
		protected System.Web.UI.HtmlControls.HtmlInputText year;
		
		protected System.Web.UI.HtmlControls.HtmlInputText title;
		
		protected System.Web.UI.HtmlControls.HtmlInputText bibname;
		
		protected System.Web.UI.HtmlControls.HtmlInputText name;
		
		protected System.Web.UI.WebControls.CheckBox checkbox;
		
		protected System.Web.UI.HtmlControls.HtmlInputText corpauth;
		
		protected System.Web.UI.HtmlControls.HtmlInputText pub;
		
		protected System.Web.UI.HtmlControls.HtmlInputText city;
		
		protected System.Web.UI.HtmlControls.HtmlInputText country;
		
		protected System.Web.UI.HtmlControls.HtmlInputText journaltitle;
		
		protected System.Web.UI.HtmlControls.HtmlInputText journalauth;
		
		protected System.Web.UI.HtmlControls.HtmlInputText volume;
		
		protected System.Web.UI.HtmlControls.HtmlInputText issue;
		
		protected System.Web.UI.HtmlControls.HtmlInputText issn;
		
		protected System.Web.UI.HtmlControls.HtmlInputText isbn;
		
		protected System.Web.UI.HtmlControls.HtmlInputText loc;
		
		protected System.Web.UI.HtmlControls.HtmlInputText doi;
		
		protected System.Web.UI.HtmlControls.HtmlInputText url;
		
		protected System.Web.UI.HtmlControls.HtmlInputText medium;
		
		protected System.Web.UI.HtmlControls.HtmlInputText edition;
		
		protected System.Web.UI.HtmlControls.HtmlInputText institution;
		
		protected System.Web.UI.HtmlControls.HtmlInputText publicationtype;
		
		protected System.Web.UI.HtmlControls.HtmlInputText chapter;
		
		protected System.Web.UI.HtmlControls.HtmlInputText pages;
		
		protected System.Web.UI.HtmlControls.HtmlInputText series;
		
		protected System.Web.UI.HtmlControls.HtmlInputText org;
		
		protected System.Web.UI.HtmlControls.HtmlInputText university;
		
		protected System.Web.UI.HtmlControls.HtmlInputText editor;
		
		protected System.Web.UI.HtmlControls.HtmlInputText translator;
		
		protected System.Web.UI.HtmlControls.HtmlInputText etcetera;
		
		protected System.Web.UI.HtmlControls.HtmlTextArea annotation;
		
		protected System.Web.UI.WebControls.Button submit;
	}
}
