// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace WebBIblio {
	
	
	public partial class Maker {
		
		protected System.Web.UI.HtmlControls.HtmlSelect bibstyle;
		
		protected System.Web.UI.HtmlControls.HtmlSelect bibformat;
		
		protected System.Web.UI.HtmlControls.HtmlSelect bibentry;
		
		protected System.Web.UI.WebControls.Button submit;
	}
}
